---
title: "git_00"
author: "Gorge Rodriguez"
date: "Summer 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
I painted her a gushing thing,  
With years about a score;  
I little thought to find they were  
A least a dozen more;  
My fancy gave her eyes of blue,  
A curly auburn head:  
I came to find the blue a green,  
The auburn turned to red.  

## Second Verse
There sandy seems the golden sky  
And golden seems the sandy plain.  
No habitation meets the eye  
Unless in the horizon rim,  
Some halfway up the limestone wall  

## Third Verse
The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  

## Last Verse
The sun was shining on the sea,  
   Shining with all his might:  
He did his very best to make  
   The billows smooth and bright—  
And this was odd, because it was  
   The middle of the night.  

The moon was shining sulkily,  
   Because she thought the sun  
Had got no business to be there  
   After the day was done—  
"It's very rude of him," she said,  
   "To come and spoil the fun!"  
